services:
#    mmarchio_doctrine_ui.example:
#        class: mmarchio\mmarchioDoctrineUIBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    mmarchio_doctrine_ui.api:
        class: mmarchio\mmarchioDoctrineUIBundle\doctrineAPI
        arguments: []
